SCREEN_W = 600
SCREEN_H = 600

BLOCK_SIZE = 27
BLOCK_COLOR = "dark red"

BOARD_BLOCKS_W = 10
BOARD_BLOCKS_H = 20
BOARD_POS_X = 20
BOARD_POS_Y = 20
BOARD_SIZE_W = BOARD_BLOCKS_W * BLOCK_SIZE
BOARD_SIZE_H = BOARD_BLOCKS_H * BLOCK_SIZE

POINTS_COLOR = "dark blue"
POINTS_FONT_SIZE = 30
POINTS_POS_X = 340
POINTS_POS_Y = 150

INFO_COLOR = "green"
INFO_FONT_SIZE = 18
INFO_POS_X = 330
INFO_POS_Y = 520

BG_COLOR = "darkcyan"
FRAME_OUTER_SHADOW = "grey1"
FRAME_BORDER = "blue"
FRAME_INNER = "grey50"